### ISSUE TITLE
Html 상에서도 구현

### ISSUE THREAD

**Issue by LeeGeonwoo22** [LeeGeonwoo22/Flutter_Calendar#2]
## Hint

Flutter 웹에서는 모바일 플랫폼과 비교하여 데이터베이스 액세스에 대해 다른 접근 방식을 사용해야 합니다. 웹 환경에서는 라이브러리 dart:io및 파일 기반 데이터베이스 작업이 불가능합니다. 대신 moor_web웹 데이터베이스 작업에 사용할 수 있습니다.

moor_web다음은 Flutter 웹에서 데이터베이스를 설정하는 방법의 예입니다 .

먼저 파일에 필요한 종속성을 추가합니다 pubspec.yaml.
```
dependencies:
  drift: ^2.2.0
  drift_generator: ^2.2.0
  drift_dev: ^2.2.0
  drift_web_dev: ^2.2.0
  moor: ^5.6.0
  moor_flutter: ^5.6.0
  moor_web: ^5.6.0
  build_runner: ^2.0.3
  drift_dev_web: ^2.2.0
  drift_flutter: ^2.2.0
```
1. drift및 다음을 사용하여 데이터베이스를 설정하십시오 moor_web.
```
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:moor/moor.dart';
import 'package:moor/moor_web.dart';
import 'package:moor_flutter/moor_flutter.dart';
import 'package:drift_flutter/drift_flutter.dart';

part 'drift_database.g.dart';

@DataClassName('Schedule')
class Schedules extends Table {
  IntColumn get id => integer().autoIncrement()();
  // ... other columns
}

@DataClassName('CategoryColor')
class CategoryColors extends Table {
  IntColumn get id => integer().autoIncrement()();
  // ... other columns
}

@DriftDatabase(tables: [Schedules, CategoryColors])
class LocalDatabase extends _$LocalDatabase {
  LocalDatabase(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => 1;
}

@DriftDatabase(tables: [Schedules, CategoryColors])
class NativeLocalDatabase extends _$NativeLocalDatabase {
  NativeLocalDatabase(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => 1;
}
```
3. moor_web데이터베이스 연결을 설정하는 데 사용합니다 .
```
@DriftDatabase(tables: [Schedules, CategoryColors])
class WebLocalDatabase extends _$WebLocalDatabase {
  WebLocalDatabase(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => 1;
}
```
flutter pub get새 종속성을 가져오기 위해 실행하고, flutter pub run build_runner build필요한 파일을 생성하기 위해 실행 하세요 .

이제 애플리케이션에서 플랫폼(네이티브 또는 웹)을 기반으로 적절한 데이터베이스 구현을 사용할 수 있습니다.

- 출처 chatGPT
